import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./styles/globals.css";
import "./styles/reset.css";
import ClientWrapper from "./ClientWrapper";
import { Providers } from "@/Components/Providers";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const nunito = Nunito({ 
  weight: '700',
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Providers>
          <ClientWrapper>{children}</ClientWrapper>
        </Providers>
        <ToastContainer
          position="bottom-left"
          closeOnClick
          theme="dark"
          draggable
          pauseOnHover
        />
      </body>
    </html>
  );
}
